services:
  homeassistant:
    container_name: homeassistant
    image: "ghcr.io/home-assistant/home-assistant:stable@sha256:aed891b8f801072302815b4b0fab5adb714182967e9d2e2d4a2be558241c73ad"
    volumes:
      - ./config:/config
      - /etc/localtime:/etc/localtime:ro
      # Mount the integration code into the container
      - ./custom_components/indygo_pool:/config/custom_components/indygo_pool
    ports:
      - "8123:8123"
    restart: unless-stopped
    environment:
      - TZ=Europe/Paris
