services:
  homeassistant:
    container_name: homeassistant
    image: "ghcr.io/home-assistant/home-assistant:stable@sha256:0e091dfce3068339c3e1d14382e6c34141e05cd589a1972ebd4d9a8e6b5d8969"
    volumes:
      - ./config:/config
      - /etc/localtime:/etc/localtime:ro
      # Mount the integration code into the container
      - ./custom_components/indygo_pool:/config/custom_components/indygo_pool
    ports:
      - "8123:8123"
    restart: unless-stopped
    environment:
      - TZ=Europe/Paris
