services:
  homeassistant:
    container_name: homeassistant
    image: "ghcr.io/home-assistant/home-assistant:stable@sha256:ff875078181a0383bf3fca9f061be12d6180896dbd531de04e094e25505b0bb9"
    volumes:
      - ./config:/config
      - /etc/localtime:/etc/localtime:ro
      # Mount the integration code into the container
      - ./custom_components/indygo_pool:/config/custom_components/indygo_pool
    ports:
      - "8123:8123"
    restart: unless-stopped
    environment:
      - TZ=Europe/Paris
